name: local_auth_example
description: Demonstrates how to use the local_auth plugin.
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth:
    # When depending on this package from a real application you should use:
    #   local_auth: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  local_auth_android:
    git: https://github.com/kumsumit/local_auth_android.git
  local_auth_darwin:
    git: https://github.com/kumsumit/local_auth_darwin.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
